[profile.default]
optimizer = true
optimizer_runs = 200

src = "src"
out = "out"
libs = ["lib", "script"]
auto_detect_solc = true


remappings = [
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@uniswap/v3-core/=lib/v3-core/",
]

[rpc_endpoints]
goerli = "https://goerli.drpc.org/"
ethereum = "https://eth.llamarpc.com"


[invariant] 
fail_on_revert = false
runs = 4
depth = 1024

[fuzz]
runs = 10000
max_test_rejects = 150000